# Generated by Django 5.0 on 2023-12-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_page', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medium_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
