# Generated by Django 5.0 on 2023-12-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcalculations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='high_rate',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='low_rate',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='medium_rate',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='rate_per_page',
        ),
        migrations.AddField(
            model_name='rate',
            name='complexity',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_type',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('dtp', 'DTP')], default='web', max_length=10),
        ),
    ]
