# Generated by Django 5.0.1 on 2024-01-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcalculations', '0002_remove_rate_category_remove_rate_high_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=70)),
                ('hist_rate_type', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('dtp', 'DTP')], default='web', max_length=10)),
                ('hist_complexity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('hist_num_pages', models.CharField(max_length=100)),
                ('hist_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
