# Generated by Django 5.0.1 on 2024-01-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcalculations', '0003_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='hist_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
