# Generated by Django 5.0.1 on 2024-01-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcalculations', '0004_alter_history_hist_rate_alter_rate_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='user',
            new_name='user_his',
        ),
    ]
